In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import os
sns.set()
os.getcwd()

'e:\\PythonDevelopment\\logisticRegression\\regression'

In [2]:
rawDataPass = pd.read_excel('E:\\PythonDevelopment\\logisticRegression\\source\\convertedData\\rawDataCleaned\\XLSX/Passed.xlsx')

rawDataPass['Admitted'] = 1
rawDataPass

Points  Admitted
0     83.12         1
1     79.36         1
2     74.80         1
3     73.36         1
4     13.96         1
..      ...       ...
370   33.28         1
371   89.92         1
372   73.84         1
373   73.76         1
374   54.40         1

[375 rows x 2 columns]

In [3]:
rawDataFail = pd.read_excel('E:\\PythonDevelopment\\logisticRegression\\source\\convertedData\\rawDataCleaned\\XLSX/Failed.xlsx')

rawDataFail['Admitted'] = 0
rawDataFail

Points  Admitted
0     47.20         0
1     95.60         0
2     94.64         0
3     91.04         0
4     86.04         0
..      ...       ...
175   72.00         0
176   67.80         0
177   65.84         0
178   59.88         0
179   43.28         0

[180 rows x 2 columns]

In [4]:
data = pd.concat([rawDataPass, rawDataFail])
data

Points  Admitted
0     83.12         1
1     79.36         1
2     74.80         1
3     73.36         1
4     13.96         1
..      ...       ...
175   72.00         0
176   67.80         0
177   65.84         0
178   59.88         0
179   43.28         0

[555 rows x 2 columns]

#### Building the regression 

In [5]:
y = data['Admitted'] # dependent variable
x1 = data['Points'] # independent variable

In [6]:
x = sm.add_constant(x1)
regLog = sm.Logit(y,x)
resultsLog = regLog.fit()

Optimization terminated successfully.
         Current function value: 0.555184
         Iterations 6


In [7]:
resultsLog.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  555
Model:                          Logit   Df Residuals:                      553
Method:                           MLE   Df Model:                            1
Date:                Sun, 19 Jul 2020   Pseudo R-squ.:                  0.1189
Time:                        00:30:49   Log-Likelihood:                -308.13
converged:                       True   LL-Null:                       -349.70
Covariance Type:            nonrobust   LLR p-value:                 7.640e-20
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.0742      0.457     -6.728      0.000      -3.970      -2.179
Points         0.0558      0.007      8.372      0.000       0.043       0.069
==============================================================================
"""

#### Predicting

In [8]:
resultsLog.predict()

array([0.82640484, 0.7942458 , 0.7495956 , 0.73422509, 0.09146907,
       0.94160372, 0.91992489, 0.85109856, 0.83640627, 0.74027341,
       0.88694873, 0.87232424, 0.86855162, 0.86855162, 0.8561148 ,
       0.85109856, 0.85081569, 0.85081569, 0.84996443, 0.8468089 ,
       0.84593891, 0.84447997, 0.84271438, 0.84271438, 0.84241853,
       0.83943516, 0.8333316 , 0.82640484, 0.82608464, 0.82155293,
       0.81659551, 0.81458286, 0.81221326, 0.81119061, 0.80947671,
       0.80947671, 0.80844268, 0.80705731, 0.80566433, 0.8039124 ,
       0.80214855, 0.7975067 , 0.79642403, 0.79497379, 0.7942458 ,
       0.79351589, 0.78983766, 0.775424  , 0.75746519, 0.7508494 ,
       0.7495956 , 0.74917673, 0.74113012, 0.73160561, 0.73160561,
       0.72051681, 0.71418605, 0.71281832, 0.71007117, 0.70961181,
       0.70592145, 0.7031358 , 0.67495615, 0.66955085, 0.66658341,
       0.65910718, 0.65003036, 0.64748927, 0.64391771, 0.64289429,
       0.63621062, 0.63207111, 0.61320903, 0.60417851, 0.59076

In [9]:
np.array(data['Admitted'])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [10]:
cmdf = pd.DataFrame(resultsLog.pred_table())
cmdf.columns = ['Predicted 0', 'Predicted 1']
cmdf = cmdf.rename(index={0:'Actual 0', 1:'Actual 1'})
cmdf
# confusion matrix

Predicted 0  Predicted 1
Actual 0         71.0        109.0
Actual 1         39.0        336.0

In [11]:
# 71 observations the model predicted 0 and it was 0
# 109 observations the model predicted 0 and it was 1
# 336 observations the model predicted 1 and it was 1
# 39 observations the model predicted 1 and it was 0

#### Testing

In [16]:
test = pd.read_excel('E:\\PythonDevelopment\\logisticRegression\\source\\testing/testing.xlsx')
test

Points  Admitted
0    83.33         1
1    83.88         1
2    79.48         1
3    78.80         1
4    72.80         1
5    73.20         1
6    69.12         1
7    66.76         1
8    59.15         1
9    56.12         1
10   30.88         0
11   39.68         0
12   44.68         0
13   50.08         0
14   50.52         0
15   44.68         1
16   45.96         0

In [19]:
testActual = test['Admitted']
testData = test.drop(['Admitted'], axis=1)
testData = sm.add_constant(testData)
testData


const  Points
0     1.0   83.33
1     1.0   83.88
2     1.0   79.48
3     1.0   78.80
4     1.0   72.80
5     1.0   73.20
6     1.0   69.12
7     1.0   66.76
8     1.0   59.15
9     1.0   56.12
10    1.0   30.88
11    1.0   39.68
12    1.0   44.68
13    1.0   50.08
14    1.0   50.52
15    1.0   44.68
16    1.0   45.96

In [21]:
def ConfusionMatrix(data, actualValues, model):
    predValues = model.predict(data)
    bins = np.array([0, 0.5, 1])
    cm = np.histogram2d(actualValues, predValues, bins = bins)[0]
    accuracy = (cm[0,0] + cm[1,1]) / cm.sum()
    return cm, accuracy


In [22]:
cm = ConfusionMatrix(testData, testActual, resultsLog)
cm

(array([[ 6.,  0.],
        [ 1., 10.]]),
 0.9411764705882353)